### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by JeroenDeKleijn** [markruys/gw2pvo#13]
I installed everything according to the main page but for me it doesn't seem to work. Am I doing something wrong, or did goodwe change the interface.

It seems the login is failing

I get the following debug output

> INFO     Starting new HTTPS connection (1): globalapi.sems.com.cn
DEBUG    Setting read timeout to 10
DEBUG    "POST /api/v1/PowerStation/GetMonitorDetailByPowerstationId HTTP/1.1" 200 281
DEBUG    {'data': None, 'hasError': False, 'msg': 'No access, please login.', 'components': {'timeSpan': 0, 'langVer': 1, 'para': None, 'api': 'http://globalapi.sems.com.cn:82/api/v1/PowerStation/GetMonitorDetailByPowerstationId'}, 'code': 100001}
INFO     Starting new HTTPS connection (1): globalapi.sems.com.cn
DEBUG    Setting read timeout to 10
DEBUG    "POST /api/v1/Common/CrossLogin HTTP/1.1" 200 362
INFO     Starting new HTTPS connection (1): euapi.sems.com.cn
DEBUG    Setting read timeout to 10
DEBUG    "POST /api/v1/PowerStation/GetMonitorDetailByPowerstationId HTTP/1.1" 500 36
WARNING  500 Server Error: Internal Server Error
INFO     Starting new HTTPS connection (1): euapi.sems.com.cn
DEBUG    Setting read timeout to 10
DEBUG    "POST /api/v1/PowerStation/GetMonitorDetailByPowerstationId HTTP/1.1" 500 36
WARNING  500 Server Error: Internal Server Error

**Comment by JeroenDeKleijn** [comment]
I made some progress:
On the old goodwe website I was allowed to have a password of 20 characters. It was no problem to logon to the SEMS portal with this password. However the mobile api only allows 16 character passwords. [insert head banging against wall]
So, I changes my password via the sems portal and then I could only enter a password of a maximum length of 16 characters

The normal mode seems to work now :), however when using the date option I now get:

> 
Traceback (most recent call last):
  File "/usr/local/bin/gw2pvo", line 9, in <module>
    load_entry_point('gw2pvo==1.2.1', 'console_scripts', 'gw2pvo')()
  File "/usr/local/lib/python3.4/dist-packages/gw2pvo/__main__.py", line 116, in run
    copy(args)
  File "/usr/local/lib/python3.4/dist-packages/gw2pvo/__main__.py", line 82, in copy
    pvo.add_day(data['entries'], temperatures)
UnboundLocalError: local variable 'temperatures' referenced before assignment
